base_url = "https://example.xyz"
title = "Your Name"
description = "A Personal Blog"

generate_feeds = true
default_language = "en"
feed_filenames = ["atom.xml"]

compile_sass = true

build_search_index = false

# theme = "zola-theme-by-g"

[markdown]
highlight_code = true

[extra]
sections = ["about", "blog", "projects"] # order in which sections are displayed

theme.default = "light"
theme.dark_icon = "🕶️"
theme.light_icon = "👓"

social.cv = "/files/yourcv.pdf"
social.dblp = "https://dblp.org/pid/000/0000.html"
social.email = "mailto:your-email@example.com"
social.github = "https://github.com/yourusername"
social.google_scholar = "https://scholar.google.com/citations?user=youruserid"
social.keybase = "https://keybase.io/yourusername"
social.linkedin = "https://www.linkedin.com/in/yourusername/"
social.mastodon = "https://mastodon.social/@yourusername"
social.orcid = "https://orcid.org/0000-0000-0000-0000"
social.rss = "/atom.xml"
social.twitter = "https://twitter.com/yourusername"

copyright.link = "https://creativecommons.org/licenses/by-nc-sa/4.0/"
copyright.icons = ["cc", "by", "nc", "sa"] # cc, by, nc, sa, publicdomain
